### ISSUE TITLE
Support of async and await

### ISSUE THREAD

**Issue by Exti** [HerrLoesch/DynamicSpecs#19]
At the moment it is possible to use async and await in the test methods. But in Given(), and When() it is currently not supported (it will not wait).

Please can you add this feature?

Thanks Andreas

**Comment by Exti** [comment]
Oh - I found the Issue "Provide asyncronouse Given and When methods.", so my request is a dublicate.

**Comment by HerrLoesch** [comment]
Duplicate of #4
