### ISSUE TITLE
Suggestion: Add "EndState" for Workflow Position

### ISSUE THREAD

**Issue by Exti** [HerrLoesch/DynamicSpecs#3]
Currently it is only possible to use a configuration for the phases given, when, create SUT and type registration. We would also need one after each specification to use for cleanup.

Greetings Andreas

**Comment by HerrLoesch** [comment]
It is implemented for NUnit but I can not publish the fix on NuGet because MS Test has an issues I have to figure out...

**Comment by HerrLoesch** [comment]
In version1.0.9.0 you'll find two new workflow steps for extensions. With these you can inject behavior after each then step or after the whole spec.
